name: Deploy Smoke Test

on:
  workflow_run:
    workflows: ["Post Merge Validation"]
    types: [completed]

jobs:

  wait-render:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Render
        run: |
          echo "Aguardando deploy do Render..."
          for i in {1..40}; do
            if curl -s https://ps-empresa.onrender.com/actuator/health | grep UP; then
              echo "Render online!"
              exit 0
            fi
            sleep 15
          done
          echo "Render n√£o subiu"
          exit 1


  smoke-test:
    needs: wait-render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout automation
        uses: actions/checkout@v4
        with:
          repository: LuisLipinski/ps_automacao_backend
          path: qa-tests
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: qa-tests
        run: npm install

      - name: Install Playwright
        working-directory: qa-tests
        run: npx playwright install --with-deps

      - name: Run Deploy Smoke
        working-directory: qa-tests
        env:
          PS_EMPRESA_URL: https://ps-empresa.onrender.com
        run: npm run empresa:smoke:render
